trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildSteps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.16'

      - task: npmAuthenticate@0
        inputs:
          workingFile: '.npmrc'
          customEndpoint: 'vscode-gather-python-program-analysis'

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo 'registry=https://pkgs.dev.azure.com/msresearch/_packaging/MSR-Python-Analysis/npm/registry/.' > .npmrc
            echo 'always-auth=true' >> .npmrc
            echo '' >> .npmrc
            echo '; begin auth token' >> .npmrc
            echo '//pkgs.dev.azure.com/msresearch/_packaging/MSR-Python-Analysis/npm/registry/:username=msresearch' >> .npmrc
            echo '//pkgs.dev.azure.com/msresearch/_packaging/MSR-Python-Analysis/npm/registry/:_password=$(NPM_TOKEN_GATHER_DUMMY)' >> .npmrc
            echo '//pkgs.dev.azure.com/msresearch/_packaging/MSR-Python-Analysis/npm/registry/:email=npm requires email to be set but doesnt use the value' >> .npmrc
            echo '//pkgs.dev.azure.com/msresearch/_packaging/MSR-Python-Analysis/npm/:username=msresearch' >> .npmrc
            echo '//pkgs.dev.azure.com/msresearch/_packaging/MSR-Python-Analysis/npm/:_password=$(NPM_TOKEN_GATHER_DUMMY)' >> .npmrc
            echo '//pkgs.dev.azure.com/msresearch/_packaging/MSR-Python-Analysis/npm/:email=npm requires email to be set but doesnt use the value' >> .npmrc
            echo '; end auth token' >> .npmrc
            echo '' >> .npmrc

      - script: npm i
        displayName: Install dependencies

      - script: npm run prepublish
        displayName: Build
