trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildSteps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.16'

      - script: npm ci
        displayName: Install dependencies

      - script: npm run prepublish
        displayName: Build
